const fetch = require('node-fetch');
const fs = require('fs');
const path = require('path');

async function fetchTweets() {
    const baseUrl = 'https://api.x.ai/v1/chat/completions';
    
    const funnyPrompt = `You are OJ Simpson's inner monologue. Generate 50 tweet/thought pairs. For each pair, provide a plausible tweet that OJ might have written, followed by your darkly humorous inner thoughts about it. Make the inner thoughts subtly reference the murders while maintaining plausible deniability. Format in JSON array. Example format:
    {
        "tweet": "Just played 18 holes of golf today!",
        "thoughts": "Golf is all about precision and choosing the right tools for the job... just like other hobbies I may or may not have experience with... 😉"
    }`;
    
    const wisdomPrompt = `You are OJ Simpson's inner monologue. Generate 50 different tweet/thought pairs about life lessons and wisdom. For each pair, provide a plausible tweet that OJ might have written, followed by your darkly humorous inner thoughts about it. Make the inner thoughts subtly reference the murders while maintaining plausible deniability. Format in JSON array. Example format:
    {
        "tweet": "Life teaches you to appreciate the little things.",
        "thoughts": "Like how a simple pair of gloves can make or break your whole day... if you know what I mean 😏"
    }`;

    try {
        console.log("Fetching tweets...");
        
        // Fetch funny tweets
        const funnyResponse = await fetch(baseUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${process.env.X_AI_API_KEY}`
            },
            body: JSON.stringify({
                messages: [
                    { role: "system", content: "You are OJ Simpson's inner voice. Be darkly humorous but maintain plausible deniability." },
                    { role: "user", content: funnyPrompt }
                ],
                model: "grok-beta",
                stream: false
            })
        });

        const funnyData = await funnyResponse.json();
        
        // Fetch wisdom tweets
        const wisdomResponse = await fetch(baseUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${process.env.X_AI_API_KEY}`
            },
            body: JSON.stringify({
                messages: [
                    { role: "system", content: "You are OJ Simpson's inner voice. Be darkly humorous but maintain plausible deniability." },
                    { role: "user", content: wisdomPrompt }
                ],
                model: "grok-beta",
                stream: false
            })
        });

        const wisdomData = await wisdomResponse.json();

        // Parse the responses
        const funnyContent = funnyData.choices[0].message.content;
        const wisdomContent = wisdomData.choices[0].message.content;

        // Extract JSON arrays from the content
        const funnyTweets = JSON.parse(funnyContent.substring(
            funnyContent.indexOf('['),
            funnyContent.lastIndexOf(']') + 1
        ));
        
        const wisdomTweets = JSON.parse(wisdomContent.substring(
            wisdomContent.indexOf('['),
            wisdomContent.lastIndexOf(']') + 1
        ));

        // Generate the new tweets.js content
        const tweetsFileContent = `// Auto-generated by test-fetch.js
export const funnyTweets = ${JSON.stringify(funnyTweets, null, 2)};

export const wisdomTweets = ${JSON.stringify(wisdomTweets, null, 2)};
`;

        // Write to tweets.js
        const tweetsPath = path.join(__dirname, '../src/data/tweets.js');
        fs.writeFileSync(tweetsPath, tweetsFileContent);

        console.log(`Successfully updated ${tweetsPath} with ${funnyTweets.length} funny tweets and ${wisdomTweets.length} wisdom tweets!`);

        // Also save raw responses for reference
        const responsesPath = path.join(__dirname, '../src/data/raw_responses.json');
        fs.writeFileSync(responsesPath, JSON.stringify({
            funny: funnyData,
            wisdom: wisdomData
        }, null, 2));

        console.log(`Raw responses saved to ${responsesPath}`);

    } catch (error) {
        console.error("Error:", error);
        if (error.message.includes('JSON')) {
            console.log("Raw response content:");
            console.log(funnyData?.choices[0]?.message?.content);
            console.log(wisdomData?.choices[0]?.message?.content);
        }
    }
}

fetchTweets();