name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate config
        run: |
          echo "const openai = new OpenAI({
            apiKey: '${{ secrets.TWITTER_API_KEY }}',
            baseURL: 'https://api.x.ai/v1',
          });" > config.js
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .